# Generated by Django 5.2.5 on 2025-08-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
